version: "3.8"


services:
  database:
    image: "postgres:latest"
    build: ./database
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - "omop_data:/var/lib/postgresql/data"

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - CDM_SCHEMA
      - VOCAB_SCHEMA
    restart: unless-stopped

volumes:
  omop_data: